import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
            Scanner sc = new Scanner(System.in);
                    int n = Integer.parseInt(sc.nextLine().trim());
                            int[] numbers = new int[n];
                                    
                                            for (int i = 0; i < n; i++) {
                                                        numbers[i] = Integer.parseInt(sc.nextLine().trim());
                                                                }
                                                                        
                                                                                int maxSum = -1;
                                                                                        // 모든 서로 다른 3개의 숫자 조합에 대해 검사
                                                                                                for (int i = 0; i < n; i++) {
                                                                                                            for (int j = i + 1; j < n; j++) {
                                                                                                                            for (int k = j + 1; k < n; k++) {
                                                                                                                                                if (noCarry(numbers[i], numbers[j], numbers[k])) {
                                                                                                                                                                        int sum = numbers[i] + numbers[j] + numbers[k];
                                                                                                                                                                                                if (sum > maxSum) {
                                                                                                                                                                                                                            maxSum = sum;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            System.out.println(maxSum);
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        // 세 숫자를 자리수별로 더했을 때 carry가 발생하는지 검사하는 함수
                                                                                                                                                                                                                                                                                                                                            private static boolean noCarry(int a, int b, int c) {
                                                                                                                                                                                                                                                                                                                                                    // 세 숫자 중 하나라도 0이 아니라면 계속 반복
                                                                                                                                                                                                                                                                                                                                                            while (a > 0 || b > 0 || c > 0) {
                                                                                                                                                                                                                                                                                                                                                                        int digitA = a % 10;
                                                                                                                                                                                                                                                                                                                                                                                    int digitB = b % 10;
                                                                                                                                                                                                                                                                                                                                                                                                int digitC = c % 10;
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                        // 현재 자리에서 세 숫자의 합이 10 이상이면 carry 발생
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (digitA + digitB + digitC >= 10) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 다음 자릿수로 이동
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a /= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b /= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c /= 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                