import java.util.*;
public class Main {
    // A helper class to store each person's position and score.
        static class Person {
                int pos;
                        int score;
                                Person(int pos, int score) {
                                            this.pos = pos;
                                                        this.score = score;
                                                                }
                                                                    }
                                                                        public static void main(String[] args) {
                                                                                Scanner sc = new Scanner(System.in);
                                                                                        
                                                                                                // Read N and K
                                                                                                        int N = sc.nextInt();
                                                                                                                int K = sc.nextInt();
                                                                                                                        
                                                                                                                                // Read each person's data and store them in an array.
                                                                                                                                        Person[] persons = new Person[N];
                                                                                                                                                for (int i = 0; i < N; i++) {
                                                                                                                                                            int pos = sc.nextInt();
                                                                                                                                                                        String letter = sc.next();
                                                                                                                                                                                    // 'G' gives 1 point, 'H' gives 2 points.
                                                                                                                                                                                                int score = letter.equals("G") ? 1 : 2;
                                                                                                                                                                                                            persons[i] = new Person(pos, score);
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    // Sort persons by their position.
                                                                                                                                                                                                                                            Arrays.sort(persons, Comparator.comparingInt(p -> p.pos));
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            int maxScore = 0;
                                                                                                                                                                                                                                                                    // Try every candidate left endpoint (which is a person's position)
                                                                                                                                                                                                                                                                            for (int i = 0; i < N; i++) {
                                                                                                                                                                                                                                                                                        int left = persons[i].pos;
                                                                                                                                                                                                                                                                                                    int rightLimit = left + K;
                                                                                                                                                                                                                                                                                                                int currScore = 0;
                                                                                                                                                                                                                                                                                                                            // Since the persons are sorted, we only need to look ahead.
                                                                                                                                                                                                                                                                                                                                        for (int j = i; j < N; j++) {
                                                                                                                                                                                                                                                                                                                                                        if (persons[j].pos <= rightLimit) {
                                                                                                                                                                                                                                                                                                                                                                            currScore += persons[j].score;
                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        maxScore = Math.max(maxScore, currScore);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Output the maximum score obtainable.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println(maxScore);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            